import { Product } from './types';

export const products: Product[] = [
  {
    id: 1,
    name: "Ethiopian Yirgacheffe",
    origin: "Ethiopia",
    category: "Single Origin",
    price: 24.99,
    weight: "340g",
    roast: "Light",
    description: "A luminous and complex coffee from the birthplace of coffee. Grown at elevations above 1,900 meters in the Yirgacheffe region, this lot showcases the terroir's signature floral and citrus characteristics. Hand-picked and naturally processed to preserve its delicate fruit notes.",
    notes: ["Jasmine", "Bergamot", "Peach", "Honey"],
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop",
    rating: 4.9,
    inStock: true,
  },
  {
    id: 2,
    name: "Colombian Supremo",
    origin: "Colombia",
    category: "Single Origin",
    price: 21.99,
    weight: "340g",
    roast: "Medium",
    description: "Sourced from the lush highlands of Huila, Colombia, this Supremo grade coffee delivers a beautifully balanced cup. Grown by third-generation farmers who employ sustainable practices, each bean is washed and sun-dried to develop its rich, caramel sweetness.",
    notes: ["Caramel", "Red Apple", "Milk Chocolate", "Walnut"],
    image: "https://images.unsplash.com/photo-1611854779393-1b2da9d400ce?w=600&h=600&fit=crop",
    rating: 4.7,
    inStock: true,
  },
  {
    id: 3,
    name: "Midnight Velvet Blend",
    origin: "Brazil & Guatemala",
    category: "Blend",
    price: 19.99,
    weight: "340g",
    roast: "Dark",
    description: "Our signature dark roast blend combines the chocolate richness of Brazilian Santos with the smoky depth of Guatemalan Antigua. Roasted low and slow to develop a full-bodied cup with a velvety mouthfeel and lingering finish that begs for another sip.",
    notes: ["Dark Chocolate", "Smoky Oak", "Brown Sugar", "Dried Fig"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=600&h=600&fit=crop",
    rating: 4.8,
    inStock: true,
  },
  {
    id: 4,
    name: "Sumatra Mandheling",
    origin: "Indonesia",
    category: "Single Origin",
    price: 23.49,
    weight: "340g",
    roast: "Medium-Dark",
    description: "From the volcanic soils of northern Sumatra, this wet-hulled coffee delivers an earthy, full-bodied experience unlike any other. The traditional Giling Basah processing method creates its distinctive syrupy body and complex, layered flavor profile.",
    notes: ["Cedar", "Dark Cocoa", "Tobacco", "Black Pepper"],
    image: "https://images.unsplash.com/photo-1587734195503-904fca47e0e9?w=600&h=600&fit=crop",
    rating: 4.6,
    inStock: true,
  },
  {
    id: 5,
    name: "Morning Ritual Blend",
    origin: "Ethiopia & Costa Rica",
    category: "Blend",
    price: 18.99,
    weight: "340g",
    roast: "Medium",
    description: "Crafted for the daily coffee lover, this blend marries the bright, fruity qualities of natural Ethiopian with the clean sweetness of Costa Rican Tarrazú. The result is an approachable yet sophisticated cup that shines whether black or with milk.",
    notes: ["Blueberry", "Toasted Almond", "Vanilla", "Citrus Zest"],
    image: "https://images.unsplash.com/photo-1498804103079-a6351b050096?w=600&h=600&fit=crop",
    rating: 4.5,
    inStock: true,
  },
  {
    id: 6,
    name: "Kenya AA Nyeri",
    origin: "Kenya",
    category: "Single Origin",
    price: 27.99,
    weight: "340g",
    roast: "Light-Medium",
    description: "An exceptional AA grade from the famed Nyeri county, grown on the slopes of Mount Kenya at 1,800 meters. Double-washed and meticulously sorted, this lot delivers the vibrant acidity and wine-like complexity that Kenyan coffees are celebrated for worldwide.",
    notes: ["Blackcurrant", "Grapefruit", "Tomato", "Raw Honey"],
    image: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=600&h=600&fit=crop",
    rating: 4.8,
    inStock: true,
  },
];

export const categories = ["All", "Single Origin", "Blend"];
export const roastLevels = ["All", "Light", "Light-Medium", "Medium", "Medium-Dark", "Dark"];
